apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: gke-fui-dev-cl
    tags:
      - project:fui
      - region:cl
      - platform:gke
      - cluster_name:gke-fui-dev-cl

  features:
    orchestratorExplorer:
      enabled: true