apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datadog-monitoring-dev

resources:
  - ../../base
  - namespace.yaml
  - secretproviderclass.yaml
  - secretsync.yaml

patches:
  - path: datadog-agent-patch.yaml
    target:
      kind: DatadogAgent
      name: datadog