apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: datadog-secret
spec:
  serviceAccountName: datadog-secret-sync
  secretProviderClassName: datadog-api-sm
  secretObject:
    type: Opaque
    data:
      - sourcePath: "api-key"
        targetKey: "api-key"