apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-api-sm
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/gcp-fui-dev/secrets/apikey_datadog_dev/versions/1"
        path: "api-key"